#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gpu:1
#SBATCH --job-name=Augment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

# install additional packages
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

# verify installation
python -c "import clip; print(f'CLIP available models: {clip.available_models()}')"